"""Project Athena textbook MVP domain primitives."""

from .assignment import (
    AssignmentConflictError,
    AssignmentNotFoundError,
    AssignmentResolver,
    EditionRegistration,
    ResolvedTextbook,
    TeachingAuthorization,
    TeachingScope,
    TeachingScopeUnauthorizedError,
    TextbookAssignment,
    TextbookEditionInactiveError,
    TextbookEditionStatus,
    WorkspaceTextbookPin,
    pin_workspace,
)
from .evidence import BoundingBox, EvidenceAnchor, EvidenceType, TextbookEdition
from .lesson_plan import (
    LEGACY_LESSON_PLAN_SCHEMA_VERSION,
    LESSON_PLAN_SCHEMA_VERSION,
    ExperimentMode,
    LessonExperiment,
    LessonPlanContent,
    LessonPlanRevisionSource,
    LessonPlanStatus,
    TopicCoverageStatus,
    TopicEvidenceCoverage,
    build_deterministic_lesson_plan,
)
from .planning import (
    LessonBudget,
    LessonSegment,
    LessonSession,
    LessonSessionKind,
    SegmentPriority,
)
from .scope import GenerationTask, UnsupportedTaskError, require_supported_task
from .slide_storyboard import (
    DEFAULT_STORYBOARD_TEMPLATE_ID,
    DEFAULT_STORYBOARD_TEMPLATE_VERSION,
    SLIDE_STORYBOARD_SCHEMA_VERSION,
    SlideLayout,
    SlideStoryboardContent,
    SlideStoryboardRevisionSource,
    SlideStoryboardStatus,
    StoryboardSlide,
    build_deterministic_storyboard,
    validate_storyboard_against_lesson,
)

__all__ = [
    "AssignmentConflictError",
    "AssignmentNotFoundError",
    "AssignmentResolver",
    "BoundingBox",
    "DEFAULT_STORYBOARD_TEMPLATE_ID",
    "DEFAULT_STORYBOARD_TEMPLATE_VERSION",
    "EditionRegistration",
    "EvidenceAnchor",
    "EvidenceType",
    "ExperimentMode",
    "GenerationTask",
    "LEGACY_LESSON_PLAN_SCHEMA_VERSION",
    "LESSON_PLAN_SCHEMA_VERSION",
    "LessonBudget",
    "LessonPlanContent",
    "LessonPlanRevisionSource",
    "LessonPlanStatus",
    "LessonExperiment",
    "LessonSegment",
    "LessonSession",
    "LessonSessionKind",
    "ResolvedTextbook",
    "SegmentPriority",
    "SLIDE_STORYBOARD_SCHEMA_VERSION",
    "SlideLayout",
    "SlideStoryboardContent",
    "SlideStoryboardRevisionSource",
    "SlideStoryboardStatus",
    "StoryboardSlide",
    "TeachingAuthorization",
    "TeachingScope",
    "TeachingScopeUnauthorizedError",
    "TextbookAssignment",
    "TextbookEdition",
    "TextbookEditionInactiveError",
    "TextbookEditionStatus",
    "TopicCoverageStatus",
    "TopicEvidenceCoverage",
    "UnsupportedTaskError",
    "WorkspaceTextbookPin",
    "build_deterministic_lesson_plan",
    "build_deterministic_storyboard",
    "pin_workspace",
    "require_supported_task",
    "validate_storyboard_against_lesson",
]
